### ISSUE TITLE
从aihome升级至havcs，原来通过group打包的温度、湿度传感器不能被dueros识别

### ISSUE THREAD

**Issue by xia0linz1** [cnk700i/havcs#14]
从aihome升级至havcs，原来按照aihome教程所写，通过group打包温度、湿度传感器成一个template sensor，配置customize.yaml后可以被dueros识别和查询。
更换havcs后，未寻获相关教程，自行尝试如下：
保持group.yaml、configuration.yaml中相关配置不变，删除customize.yaml中相关配置，在havcs.yaml中添加如下配置：
```
sensor.livingroom:   #configuration.yaml中虚拟的template sensor
  friendly_name: 客厅传感器
  havcs_related_sensors: group.livingroom_sensors  #group.yaml中打包的组
  havcs_actions [‘query_temperature’, ‘query_humidity’]
```

测试结果不能被dueros识别。

请问该如何配置？

**Comment by cnk700i** [comment]
把日志级别调好，执行havcs.reload，如果设备属性正确日志会有输出的。
看你贴的配置标点有问题havcs_actions: ['query_temperature', 'query_humidity']
