### ISSUE TITLE
刷新token后没有新的refresh_token

### ISSUE THREAD

**Issue by acdxxx177** [cnk700i/havcs#15]
第一次通过code来换取token是有refresh_token值，但是通过refresh_token请求来刷新token返回没有refresh_token的值，导致天猫精灵的授权过期，需要重新进入测试验证，请问该如何配置

> 请求https://xxx.com/havcs_auth  grant_type=authorization_code 有refresh_token值

> 请求https://xxx.com/havcs_auth  grant_type=refresh_token 没有refresh_token值

**Comment by cnk700i** [comment]
HA自带的处理就是不会返回新refresh_token的，所以现在增加直接将旧的refresh_token返回，你更新下看看行不。不然就把超时时间调大吧。。。
