### ISSUE TITLE
纯ipv6网络授权失败

### ISSUE THREAD

**Issue by zz66** [cnk700i/havcs#28]
版本：havcs v3
模式：模式一 http模式，自建测试技能
环境：内网http访问，外网通过nginx代理，通过https访问
平台：dueros
网络条件：移动宽带，无ipv4公网ip，但外网可通过ipv6访问

按教程部署havcs v3后，无论使用HA自带的授权页面还是havcs授权页面，dueros开放平台均授权失败。
使用另一台具有公网ipv4的服务器，运行nginx，通过ipv6访问HA主机并反向代理，对外提供基于ipv4的https服务，即可授权成功。

建议：解决纯ipv6环境的授权问题。

谢谢

**Comment by LaolongVincent** [comment]
@zz66 还好看了你的问题。我宽带环境和你一样，用hass论坛的othau方法接入总是返回token不正确，正想试试cnk大佬的方法，看了你的评论，看来也只能云平台搭一个nginx服务器试试了。

**Comment by byff** [comment]
> 版本：havcs v3
> 模式：模式一 http模式，自建测试技能
> 环境：内网http访问，外网通过nginx代理，通过https访问
> 平台：dueros
> 网络条件：移动宽带，无ipv4公网ip，但外网可通过ipv6访问
> 
> 按教程部署havcs v3后，无论使用HA自带的授权页面还是havcs授权页面，dueros开放平台均授权失败。
> 使用另一台具有公网ipv4的服务器，运行nginx，通过ipv6访问HA主机并反向代理，对外提供基于ipv4的https服务，即可授权成功。
> 
> 建议：解决纯ipv6环境的授权问题。
> 
> 谢谢

这个不是插件的问题，是天猫精灵技能平台还不支持ipv6
