### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'broker'

### ISSUE THREAD

**Issue by LaughingLeeLife** [cnk700i/havcs#32]
升级了HA 和 HAVCS V3.发现有error，请大神帮忙看下。谢谢。
Home Assistant 0.113.2

Log Details (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/havcs/__init__.py:372
First occurred: 10:23:49 PM (1 occurrences)
Last logged: 10:23:49 PM

Error setting up entry configuration.yaml for havcs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 219, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/havcs/__init__.py", line 372, in async_setup_entry
    hass.data[DOMAIN][DATA_HAVCS_MQTT] = mqtt.MQTT(
TypeError: __init__() got an unexpected keyword argument 'broker'

**Comment by cnk700i** [comment]
新版本函数方法有调整，近期会更新。
